######## Sidebar ########
sidebar:
  logo:
    avatar: '[config.avatar](https://mhuig.top/)' # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
    title: '[config.title](/)' # you can set html tag like: '[<img no-lazy height="32px" src="xxx"/>](/)'
  menu:
    post: '[RSS](/)'
    blog: '[博客](https://blog.mhuig.top/)'
    about: '[关于](https://mhuig.top/)'
  # Sidebar widgets
  widget_layout:
    index: [recent] # for home/wiki/categories/tags/archives/404 pages
    page: [toc] # for pages using 'layout:page'
  widgets:
    # Recent update
    recent:
      layout: recent
      rss: /atom.xml # npm i hexo-generator-feed
      limit: 5 # Count of posts
    # TOC (valid only in layout:post/wiki)
    toc:
      layout: toc
      list_number: false
      min_depth: 2
      max_depth: 5
      fallback: recent # Use a backup widget when toc does not exist.
    # welcome
    welcome:
      layout: markdown
      title: Welcome
      content: | # support markdown
        欢迎来到 MHuiGのRSS订阅

######## Article ########
article:
  # 如果没有指定封面，是否根据 tags 作为关键词搜索封面？
  auto_cover: true # search from https://source.unsplash.com/
  # 如果没有指定 excerpt 和 description，将自动取多长的内容作为文章摘要？
  auto_excerpt: 200
  # 分类颜色
  category_color:
    '新闻稿': '#DA0F47'
  # 文章许可协议
  license: '本文采用 [GLWT（Good Luck With That，祝你好运）公共许可证](https://github.com/me-shaon/GLWTPL/blob/master/translations/LICENSE_zh-CN) 许可协议。'
  # 分享
  share: # [wechat, weibo, email, link]
  # 相关文章，需要安装插件 (for layout: post)
  # npm i hexo-related-popular-posts
  related_posts:
    enable: true
    max_count: 15
    auto_cover: true # 如果没有封面就根据 tags 作为关键词搜索封面，开了此项将不会自动从文章中提取首张图片作为封面了。



######## Comments ########
comments:
  service: # beaudar, utterances, valine, twikoo

######## Footer ########
footer:
  social:
    github:
      icon: '<img src="https://static.mhuig.top/gh/cdn-x/placeholder@1.0.3/social/08a41b181ce68.svg"/>'
      url: https://github.com/MHuiG
    music:
      icon: '<img src="https://static.mhuig.top/gh/cdn-x/placeholder@1.0.3/social/3845874.svg"/>'
      url: https://music.163.com/#/user/home?id=63035382
    contact:
      icon: '<img src="https://static.mhuig.top/gh/cdn-x/placeholder@1.0.3/social/a1b00e20f425d.svg"/>'
      url: /contact/

  sitemap:
    'RSS':
      - '[近期](/)'
      - '[分类](/categories/)'
      - '[标签](/tags/)'
      - '[归档](/archives/)'
    'Support':
      - '[博客](https://blog.mhuig.top/)'
      - '[API](https://api.mhuig.top/)'
      - '[SSL Status](https://ssl.mhuig.top/)'
      - '[Status Monitors](https://mhuig.instatus.com/)'
    '社交':
      - '[友链](https://blog.mhuig.top/pages/friends/)'
      - '[留言板](https://blog.mhuig.top/pages/about/)'
    '更多':
      - '[关于我](https://mhuig.top/)'
      - '[GitHub](https://github.com/MHuiG)'
      - '[Contact](/contact/)'
      - '[隐私政策](/privacy-policy/)'
  content: | # 支持 Markdown 格式
    本站由 [MHuiG](https://mhuig.top/) 使用 [Stellar](https://github.com/xaoxuu/hexo-theme-stellar) 主题创建，您可以在 [GitHub](https://github.com/MHG-LAB/RSSBOX) 找到本站源码
    本博客所有文章除特别声明外，均采用 [GLWT（Good Luck With That，祝你好运）公共许可证](https://github.com/me-shaon/GLWTPL/blob/master/translations/LICENSE_zh-CN) 许可协议，转载请注明出处。

######## JS Plugins ########
plugins:
  ## required plugins ##
  # jquery
  jquery: https://static.mhuig.top/npm/jquery@3.5.1/dist/jquery.min.js

  # issues api
  sitesjs: /js/plugins/sites.js
  friendsjs: /js/plugins/friends.js

  ## optional plugins ##
  # preload
  preload:
    enable: true
    service: flying_pages # instant_page, flying_pages
    instant_page: https://static.mhuig.top/gh/volantis-x/cdn-volantis@4.1.2/js/instant_page.js
    flying_pages: https://static.mhuig.top/gh/gijo-varghese/flying-pages@2.1.2/flying-pages.min.js

  # image lazyload
  # https://www.npmjs.com/package/vanilla-lazyload
  lazyload:
    enable: true # [hexo clean && hexo s] is required after changing this value.
    js: https://static.mhuig.top/npm/vanilla-lazyload@17.3.1/dist/lazyload.min.js
    transition: blur # blur, fade

  # https://scrollrevealjs.org/api/reveal.html
  scrollreveal:
    enable: #true
    js: https://static.mhuig.top/npm/scrollreveal@4.0.9/dist/scrollreveal.min.js
    distance: 8px
    duration: 500 # ms
    interval: 100 # ms
    scale: 1 # 0.1~1

  # https://fancyapps.com/docs/ui/fancybox/
  # available for {% image xxx %}
  fancybox:
    enable: true
    js: https://static.mhuig.top/npm/@fancyapps/ui@4.0/dist/fancybox.umd.js
    css: https://static.mhuig.top/npm/@fancyapps/ui@4.0/dist/fancybox.css
    # 可以处理评论区的图片（不支持 iframe 类评论系统）例如：
    # 使用valine评论可以写: .vcontent img:not(.vemoji)
    # 使用twikoo评论可以写: .tk-content img:not([class*="emo"])
    selector: .swiper-slide img,article.content img # 多个选择器用英文逗号隔开

  # swiper
  swiper:
    enable: true
    css: https://unpkg.com/swiper@6/swiper-bundle.min.css
    js: https://unpkg.com/swiper@6/swiper-bundle.min.js

style:
  darkmode: auto # auto / always / false
  theme:
    light: '#f8f8f8'
    dark: '#313438'
  animated_avatar:
    animate: auto # auto, always
    background: https://static.mhuig.top/gh/cdn-x/placeholder@1.0.2/avatar/round/rainbow64@3x.webp
  codeblock:
    scrollbar: 4px

default:
  avatar: https://static.mhuig.top/gh/cdn-x/placeholder@1.0.1/avatar/round/3442075.svg
  link: https://static.mhuig.top/gh/cdn-x/placeholder@1.0.1/link/8f277b4ee0ecd.svg
  cover: https://static.mhuig.top/gh/cdn-x/placeholder@1.0.1/cover/76b86c0226ffd.svg
  image: https://static.mhuig.top/gh/cdn-x/placeholder@1.0.1/image/2659360.svg
