# touhou rss collection 

文字:
  文文最速新闻: https://www.touhou.cc/bbs/forum.php?mod=forumdisplay&fid=48&mod=rss

视频:
  御坂14363号-东方: https://rsshub.app/bilibili/fav/699221292/1703917092
  东方音像馆: https://rsshub.app/bilibili/user/dynamic/630991474
  曦阳_231-MMD: https://rsshub.app/bilibili/user/dynamic/696721978
  乌冬院-MMD: https://rsshub.app/bilibili/user/dynamic/21529645
  Zhipr-MMD: https://rsshub.app/bilibili/user/dynamic/9496794
  芊年人间-东浅语: https://rsshub.app/bilibili/user/collection/204706570/176804
  千代敏儿-coser: https://rsshub.app/bilibili/user/dynamic/343896757
  芙兰档案: https://rsshub.app/bilibili/user/collection/1345435780/902426
  筱瑶-东方安利: https://rsshub.app/bilibili/user/collection/352163411/394719
  Z一LGW-猩东方: https://rsshub.app/bilibili/user/collection/11007230/45383
  Z一LGW-来世炸了幻想乡: https://rsshub.app/bilibili/user/channel/11007230/541095
  Z一LGW-全人类的飞上天: https://rsshub.app/bilibili/user/channel/11007230/541094
  Z一LGW-梗东方: https://rsshub.app/bilibili/user/collection/11007230/819078
  Z一LGW-聊东方了: https://rsshub.app/bilibili/user/collection/11007230/2342

音乐:
  五郎-东方音乐: https://rsshub.app/bilibili/fav/359079394/2293459894
  御坂14363号-东方音乐: https://rsshub.app/bilibili/fav/699221292/1699573092
  触手猴-钢琴演奏: https://rsshub.app/bilibili/user/dynamic/489391680
  筱瑶-钢琴演奏: https://rsshub.app/bilibili/user/dynamic/352163411
  11是谁啊-同人音乐: https://rsshub.app/bilibili/user/dynamic/1664494
  RickyRister-同人音乐: https://rsshub.app/bilibili/user/dynamic/393639419
  肥兔菌-东方音乐: https://rsshub.app/bilibili/user/dynamic/297656522
  幽闭星光-音乐社团: https://rsshub.app/bilibili/user/dynamic/23052222
  夏天的奇妙-口琴演奏: https://rsshub.app/bilibili/user/dynamic/90398168
  筱瑶-东方战斗曲: https://rsshub.app/bilibili/user/collection/352163411/439252
  筱瑶-东方组曲: https://rsshub.app/bilibili/user/collection/352163411/307424
  筱瑶-东方超还原の扒谱: https://rsshub.app/bilibili/user/collection/352163411/46832
  筱瑶-东方扒谱: https://rsshub.app/bilibili/user/channel/352163411/1672205
  筱瑶-东方暴力传教: https://rsshub.app/bilibili/user/channel/352163411/1672203
  幻梦流光交响社-东方旧作: https://rsshub.app/bilibili/user/channel/27709843/446179
  Yoshika_DK-管乐组曲: https://rsshub.app/bilibili/user/collection/39386600/611627
  榆木华-东方组曲: https://rsshub.app/bilibili/user/channel/3663104/272051

图片:
  pixiv-touhou: https://rsshub.app/pixiv/search/touhou
  pixiv-核燃黑猫: https://rsshub.app/pixiv/user/1408324
  pixiv-oO大黄Oo: https://rsshub.app/pixiv/user/9892346
  剑の冰精-同人漫画: https://rsshub.app/bilibili/user/dynamic/384431765
  百流夜-有声漫画: https://rsshub.app/bilibili/user/dynamic/195533478
  跃亮-有声漫画: https://rsshub.app/bilibili/user/dynamic/3170013
  清澈雨滴-同人漫画: https://rsshub.app/bilibili/user/dynamic/503150289
  炸鸡QwQ-配音手书: https://rsshub.app/bilibili/user/dynamic/1345435780

游戏:
  东方夜雀食堂: https://rsshub.app/bilibili/user/collection/86865890/2755
  The_495th_Comple: https://rsshub.app/bilibili/user/dynamic/1629262586
  东方妖灵传: https://rsshub.app/bilibili/user/collection/2673367/1200786

社团:
  森罗万象-音乐社团: https://rsshub.app/bilibili/user/dynamic/165906284
  瑶山百灵-音乐社团: https://rsshub.app/bilibili/user/dynamic/210232
  幻梦流光交响社-音乐社团: https://rsshub.app/bilibili/user/dynamic/27709843
  囧仙-远古の神: https://rsshub.app/bilibili/user/dynamic/12246
  伊吹小秋-搬运工: https://rsshub.app/bilibili/user/dynamic/448823
  因幡帝汉化组: https://rsshub.app/bilibili/user/dynamic/32589387
  胡逆天-爱好者: https://rsshub.app/bilibili/user/dynamic/3621415
  Z一LGW-传教士: https://rsshub.app/bilibili/user/dynamic/11007230

开发:
  touhou-midi-collection: https://github.com/AyHa1810/touhou-midi-collection/commits.atom

网站:
  touhou.cc BBS: https://www.touhou.cc/bbs/?mod=rss

站长:
  SMGoroBlog: https://blog.imc.re/atom.xml
  五郎のb站动态: /bilibili/user/dynamic/359079394
  五郎の知乎动态: /zhihu/people/activities/smgoro
  五郎の爱发电动态: /afdian/dynamic/@SummerGoro


