# touhou rss collection 

文字:
  文文最速新闻: https://www.touhou.cc/bbs/forum.php?mod=forumdisplay&fid=48&mod=rss

视频:
  御坂14363号-东方: https://rsshub.app/bilibili/fav/699221292/1703917092
  东方音像馆: https://rsshub.app/bilibili/user/dynamic/630991474
  曦阳_231-MMD: https://rsshub.app/bilibili/user/dynamic/696721978
  乌冬院-MMD: https://rsshub.app/bilibili/user/dynamic/21529645
  芊年人间-东浅语: https://rsshub.app/bilibili/user/collection/204706570/176804
  千代敏儿-coser: https://rsshub.app/bilibili/user/dynamic/343896757

音乐:
  御坂14363号-东方音乐: https://rsshub.app/bilibili/fav/699221292/1699573092
  RickyRister-东方音乐: https://rsshub.app/bilibili/user/dynamic/393639419
  肥兔菌-东方音乐: https://rsshub.app/bilibili/user/dynamic/297656522
  森罗万象-音乐社团: https://rsshub.app/bilibili/user/dynamic/165906284
  瑶山百灵-音乐社团: https://rsshub.app/bilibili/user/dynamic/210232
  11是谁啊同人音乐: https://rsshub.app/bilibili/user/dynamic/1664494
  Zhipr-MMD: https://rsshub.app/bilibili/user/dynamic/9496794
  夏天的奇妙-口琴演奏: https://rsshub.app/bilibili/user/dynamic/90398168

图片:
  pixiv-touhou: https://rsshub.app/pixiv/search/touhou/popular/safe
  剑の冰精-同人漫画: https://rsshub.app/bilibili/user/dynamic/384431765
  百流夜-有声漫画: https://rsshub.app/bilibili/user/dynamic/195533478
  跃亮-有声漫画: https://rsshub.app/bilibili/user/dynamic/3170013
  清澈雨滴-同人漫画: https://rsshub.app/bilibili/user/dynamic/503150289

游戏:
  东方夜雀食堂: https://rsshub.app/bilibili/user/collection/86865890/2755
  The_495th_Comple: https://rsshub.app/bilibili/user/dynamic/1629262586

社团:
  囧仙-远古の神: https://rsshub.app/bilibili/user/dynamic/12246
  伊吹小秋-搬运工: https://rsshub.app/bilibili/user/dynamic/448823

开发:
  touhou-midi-collection: https://github.com/AyHa1810/touhou-midi-collection/commits.atom

网站:
  touhou.cc BBS: https://www.touhou.cc/bbs/?mod=rss

站长:
  SMGoroBlog: https://blog.imc.re/atom.xml
  五郎のb站动态: /bilibili/user/dynamic/359079394
  五郎の知乎动态: /zhihu/people/activities/smgoro
  五郎の爱发电动态: /afdian/dynamic/@SummerGoro


